### PR TITLE
fixed broken cart and fixed empty cart problem

### PR DESCRIPTION
**Pull request by kimah72**
I am having trouble with branches and have created too many. Lol How do I delete them? I think I figured out to use merge when I do it next time but once things are merged I think the extra branches can be deleted. Just delete everything I made except the kimah branch. Thanks.

### CODE REVIEW

**Comment by kimah72** [comment]
I am having trouble with branches and have created too many. Lol How do I delete them? I think I figured out to use merge when I do it next time but once things are merged I think the extra branches can be deleted. Just delete everything I made except the kimah branch. Thanks.

**Review by Ganon3 — APPROVED** [review]
looks good i think

**Comment by Ganon3** [comment]
fixing the week2 issuse

**Review by Ganon3 — APPROVED** [review]
ok

**Comment by Ganon3** [comment]
ok

**Comment by Ganon3** [comment]
i think i got it

**Pull request merged**
